### ISSUE TITLE
⚠️ MUHIM ... codeni reindent qilish 

### ISSUE THREAD

**Issue by ozbeg** [akbarjondev/pokemonjon#1]
https://github.com/akbarjondev/pokemonjon/blob/8eefedca369f0352502f7fedbeb3bfb78b4aca77/js/scripts.js#L1

<img width="709" alt="Screen Shot 2020-11-23 at 00 01 30" src="https://user-images.githubusercontent.com/68459737/99914417-1b49f580-2d1f-11eb-99d7-c7d1aa15e885.png">

Reindent qilsangiz o'qishga ancha Yaxshi bo'lardi .

**Comment by akbarjondev** [comment]
Reindent qilindi
